function Header=updateHeader(CameraObj)
   RAD = 180./pi;
   DateObs = datestr(CameraObj.CamHn.time_start,'yyyy-mm-ddTHHMMSS.FFF');
   DateVec = datevec(CameraObj.CamHn.time_start);
   JD      = celestial.time.julday(DateVec(:,[3 2 1 4 5 6]));

   if (isempty(CameraObj.MouHn))
      MountGeoName = 0;
      RA  = NaN;
      Dec = NaN;
      HA  = NaN;
      LST = NaN;
      Az  = NaN;
      Alt = NaN;
      TrackingSpeed = NaN;
      isCounterWeightDown = NaN;
   else
      MountGeoName = CameraObj.MouHn.MountGeoName;
      RA  = CameraObj.MouHn.RA;
      Dec = CameraObj.MouHn.Dec;
      HA  = CameraObj.MouHn.HA;
      LST = celestial.time.lst(JD,CameraObj.MouHn.MountCoo.ObsLon./RAD,'a').*360;
      Az = CameraObj.MouHn.Az;
      Alt = CameraObj.MouHn.Alt;
      TrackingSpeed = CameraObj.MouHn.TrackingSpeed;
      isCounterWeightDown = CameraObj.MouHn.isCounterWeightDown;
   end

   Instrument = sprintf('LAST.%s.%s.%s', util.readSystemConfigFile('ObservatoryNode'), MountGeoName, CameraObj.CamGeoName); % 'LAST.node.mount.camera'
   Header = {'NAXIS',2,'number of axes';...
              'NAXIS1',size(CameraObj.CamHn.lastImage,2),'size of axis 1 (X)';...
              'NAXIS2',size(CameraObj.CamHn.lastImage,1),'size of axis 2 (Y)';...
              'BITPIX',-32,'bits per data value';...
              'BZERO',0.0,'zero point in scaling equation';...
              'BSCALE',1.0,'linear factor in scaling equation';...
              'BUNIT','ADU','physical units of the array values';...
              'IMTYPE',CameraObj.ImType,'Image type: dark/flat/focus/science/test';...
              'INTGAIN',CameraObj.Gain,'Camera internal gain level';...
              'INTOFFS',CameraObj.CamHn.offset,'Camera internal offset level';...
              'BINX',CameraObj.binning(1),'Camera binning in X-axis';...
              'BINY',CameraObj.binning(2),'Camera binning in Y-axis';...
              'ORIGIN','Weizmann Institute of Science','organization responsible for the data';...
              'TELESCOP','Celestron RASA 11','name of telescope';...
              'CAMERA',[CameraObj.CamType, ' ', CameraObj.CamModel],'Camera name';...
              'INSTRUME',Instrument,'LAST.node.mount.camera';...
              'OBSERVER','LAST','observer who acquired the data';...
              'REFERENC','NAN','bibliographic reference';...
              'EXPTIME',CameraObj.ExpTime,'Exposure time (s)';...
              'TEMP_DET',CameraObj.Temperature,'Detector temperature';...
              'COOLERPWR',CameraObj.CoolingPercentage,'Percentage of the cooling power';...
              'RA',RA,'J2000.0 R.A. [deg]';...
              'DEC',Dec,'J2000.0 Dec. [deg]';...
              'HA',HA,'Hour Angle [deg]';...
              'LST',LST,'LST [deg]';...
              'AZ',Az,'Azimuth';...
              'ALT',Alt,'Altitude';...
              'EQUINOX',2000.0,'Coordinates equinox (Julian years)';...
              'TRACKSP',TrackingSpeed,'';...
              'FOCUS',CameraObj.FocHn.Pos,'Focus value';...
              'PRFOCUS',CameraObj.FocHn.LastPos,'Previous Focus value';...
              'CWDOWN',isCounterWeightDown,'Is Counter Weight Down flag';...
              'CDELT1',0.000347,'coordinate increment along axis 1 (deg/pix)';...
              'CDELT2',0.000347,'coordinate increment along axis 2 (deg/pix)';...
              'SCALE',1.251,'Pixel scale (arcsec/pix)';...
              'DATE-OBS',DateObs,'date of the observation';...
              'JD',JD,'Julian day';...
              'MJD',JD-2400000.5,'Modified Julian day';...
              'OBJECT',CameraObj.Object,'Object/field name'};
end
