function Res=measure_small_shift(List,varargin)
% Estimate X/Y shift between images
% Input  : - A cell array containing a list of images
%            generated by e.g., imUtil.util.filelist
%          * Arbitrary number of ...,kry,val,...
% Output : - A structure array with shifts measurments.
% Exampple: List=imUtil.util.filelist('LAST*');
%           Res=obs.util.tools.measure_small_shift(List(end-1:end));
% N=20;
% for I=1:1:N, I, L.RA(I,1)=X.RA; L.Dec(I,1)=X.Dec; L.HA(I,1)=X.HA; C.takeExposure; pause(15.*1); L.RA(I,2)=X.RA; L.Dec(I,2)=X.Dec; L.HA(I,2)=X.HA; C.takeExposure; C.waitFinish; List=imUtil.util.filelist('LAST*'); Res(I).Res=obs.util.tools.measure_small_shift(List(end-1:end)); end
% for I=1:1:N, plot(I,Res(I).Res(2).MedDX,'bo'); hold on; plot(I,Res(I).Res(2).MedDY,'ro'); end
% N=120; C.ExpTime=3; for I=1:1:N, I, L.JD(I)=celestial.time.julday; L.RA(I)=X.RA; L.Dec(I)=X.Dec; L.HA(I)=X.HA; L.HATicks(I)=X.HATicks; L.DecTicks(I)=X.DecTicks;  C.takeExposure; C.waitFinish; end

SECOND_IN_DAY = 86400;


InPar = inputParser;
addOptional(InPar,'CCDSEC',[3100-500 3100+500 4700-500 4700+500]);
addOptional(InPar,'ColX','XWIN_IMAGE'); 
addOptional(InPar,'ColY','YWIN_IMAGE'); 
addOptional(InPar,'ColSN','SN'); 
addOptional(InPar,'LimitSN',20); 
addOptional(InPar,'SearchRad',10); 

parse(InPar,varargin{:});
InPar = InPar.Results;


S = FITS.read2sim(List,'CCDSEC',InPar.CCDSEC);
S = mextractor(S);
Ns = numel(S);
AstOut = match(S,S(1),'SkipWCS',true,'SearchRad',InPar.SearchRad);
ColX   = colname2ind(AstOut(1),InPar.ColX);
ColY   = colname2ind(AstOut(1),InPar.ColY);
ColSN  = colname2ind(AstOut(1),InPar.ColSN);


JD = julday(S);

Iref = 1;
Flag = S(Iref).Cat(:,ColSN)>InPar.LimitSN;

for Is=2:1:Ns
    
    
    DX = AstOut(Is).Cat(Flag,ColX)-S(Iref).Cat(Flag,ColX);
    DY = AstOut(Is).Cat(Flag,ColY)-S(Iref).Cat(Flag,ColY);
    
    Res(Is).Nmatch = numel(~isnan(DX));
    Res(Is).MedDX = nanmedian(DX);
    Res(Is).MedDY = nanmedian(DY);
    Res(Is).StdDX = nanstd(DX);
    Res(Is).StdDY = nanstd(DY);
    Res(Is).DT    = JD(Is) - JD(Iref);  % time diff. [day]
    Res(Is).VelDX = Res(Is).MedDX./(Res(Is).DT.*SECOND_IN_DAY); % pix/s
    Res(Is).VelDY = Res(Is).MedDY./(Res(Is).DT.*SECOND_IN_DAY); % pix/s
    
end

